services:
  reranker-service:
    build: .
    ports:
      - "8002:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
