# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reranker_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'reranker_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16reranker_service.proto\x12\x08reranker\"1\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tdocuments\x18\x02 \x03(\t\"F\n\x0eRerankResponse\x12\x34\n\x12reranked_documents\x18\x01 \x03(\x0b\x32\x18.reranker.RankedDocument\"1\n\x0eRankedDocument\x12\x10\n\x08\x64ocument\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32Y\n\x0fRerankerService\x12\x46\n\x0fRerankDocuments\x12\x17.reranker.RerankRequest\x1a\x18.reranker.RerankResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reranker_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RERANKREQUEST']._serialized_start=36
  _globals['_RERANKREQUEST']._serialized_end=85
  _globals['_RERANKRESPONSE']._serialized_start=87
  _globals['_RERANKRESPONSE']._serialized_end=157
  _globals['_RANKEDDOCUMENT']._serialized_start=159
  _globals['_RANKEDDOCUMENT']._serialized_end=208
  _globals['_RERANKERSERVICE']._serialized_start=210
  _globals['_RERANKERSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
